### ISSUE TITLE
Problems with featured images.

### ISSUE THREAD

**Issue by renefraga** [hughrun/ghost-to-wp#7]
Hi, the tool is working, but I think something has changed in Ghost .json. I noticed that the featured images are not going to the XML, which ends up migrating only the textual part. I know we're almost in 2024, but is there still a possibility of this tool getting a new version? I would really appreciate it! Thanks!!

**Comment by hughrun** [comment]
@renefraga sorry for the delayed reply. I haven't looked at Ghost for quite a while but I'll take a look at this in the next week or two.

**Comment by hughrun** [comment]
I took a look at this but due to the way WordPress import files refer to images, this tool is really not the right one for the job if you have a lot of images.

Importing by RSS might be the best bet, or if someone (not me) made a WordPress plugin for Ghost export files that would probably be the best approach.
